### ISSUE TITLE
Question on the role of "Stop sequence"

### ISSUE THREAD

**Issue by erikmd** [elaastic/elaastic-questions#53]
**Kind:** question

Dear @FranckSilvestre @jtranier, thanks a lot for developing elaastic-questions!

I am not 100% sure if it is OK to ask such questions as a GitHub issue… if not, sorry about that :/

Regarding the role of "Stop sequence":

1. If one does not click on "Stop sequence", just on "Stop phase 2", then the phase 2 can be reopened. But is it the only thing done by "Close sequence" (preventing reopening)? If yes, is it really necessary to trigger that button "Close sequence" at some point?

2. "Close sequence" can be triggered without having clicked on "Close phase 2" nor "Close phase 1". What happens in these two cases? (If I'm not mistaken, "doing "Close sequence" if the phase 2 is running will just do the same as "Close phase 2; Close sequence", while doing "Close sequence" if the phase 1 is running will skip the phase 2 and the results won't have the two columns (Phase 1, Phase 2)?

Kind regards,
Erik

**Comment by FranckSilvestre** [comment]
Hi Erik,

Thank you for your questions.

The "Close sequence" button works exactly as you mentioned and conforms to your assumptions. In fact, this button is really useful when you launch sequences in distance or hybrid mode. It is the more efficient way to stop a sequence and prevent new participations. Reminder: in hybrid or distance mode, you don't manage phases as you do in face-to-face mode as each student play the 2 or 3 phases during his/her first connexion. 

Kind regards,
Franck

**Comment by erikmd** [comment]
Hi Franck,
OK thanks for your feedback!
(so feel free to close this question-issue now)
